# vim:noai:ts=2:sw=2
version: "3.8"
                    
services:
  db:
    environment:
      MANOVNFM_USER: mano_vnfm
      MANOVNFM_PASSWORD: mano
      MANONFVO_USER: mano_nfvo
      MANONFVO_PASSWORD: mano
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_DB: keycloak
    networks:
      default:
        aliases:
          - "mano-db"

  mano-artemis:
    image: openmsa/artemis:2.19.0
    deploy:
      replicas: 1
      placement:	
        max_replicas_per_node: 1
        constraints:	
          - "node.labels.worker==mano"

  mano-auth:
    image: jboss/keycloak:16.1.1
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.worker==mano"            
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ubiqube
      DB_VENDOR: postgres
      DB_ADDR: mano-db
      POSTGRES_ADDR: mano-db
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: "datasource_jndi_name=java:jboss/datasources/KeycloakDS"
      JAVA_OPTS: "-Djboss.as.management.blocking.timeout=600"
    ports:
      - target: 8080
        published: 8110
        protocol: tcp
        mode: ingress

  mano-nfvo:
    image: ubiqube/mano-nfvo-tm22:uat7
    volumes:
      - "/mnt/NASVolume/mano_nfvo:/opt/etsi-mano-data"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.worker==mano"
    ports:
      - target: 8080
        published: 8100
        protocol: tcp
        mode: ingress
    secrets:
      - source: vnfm.keycloak.credentials.secret
        target: keycloak.credentials.secret

  mano-vnfm:
    image: ubiqube/mano-vnfm-tm22:uat7
    volumes:
      - "/mnt/NASVolume/mano_vnfm:/opt/etsi-mano-data"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.worker==mano"
    ports:
      - target: 8080
        published: 8090
        protocol: tcp
        mode: ingress
    secrets:
      - source: nfvo.keycloak.credentials.secret
        target: keycloak.credentials.secret

secrets:
  vnfm.keycloak.credentials.secret:
    external: true
  nfvo.keycloak.credentials.secret:
    external: true



