version: "3.8"

services:
  mano-artemis:
    image: openmsa/artemis:2.19.0
    deploy:
      replicas: 1
      placement:	
        max_replicas_per_node: 1
        constraints:	
          - "node.labels.worker==app"

  mano-auth:
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.worker==app"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ubiqube
      DB_VENDOR: postgres
      DB_ADDR: mano-db
      POSTGRES_ADDR: mano-db
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
      JGROUPS_DISCOVERY_PROPERTIES: "datasource_jndi_name=java:jboss/datasources/KeycloakDS"
      JAVA_OPTS: "-Djboss.as.management.blocking.timeout=600"
    image: jboss/keycloak:16.1.1
    ports:
      - target: 8080
        published: 8110
        protocol: tcp
        mode: ingress

  db:
    networks:
      default:
        aliases:
          - "mano-db"

  mano-nfvo:
    image: oviubiqube/mano-nfvo-tm22:uat3
#    environment:
#      KEYCLOAK_RESOURCE=mano-vnfm
#      KEYCLOAK_CREDENTIALS_SECRET=xxxxxxxx
    volumes:
      - "/mnt/NASVolume/mano_nfvo:/opt/etsi-mano-data"
    deploy:
      replicas: 1
      placement:	
        max_replicas_per_node: 1
        constraints:	
          - "node.labels.worker==app"
    ports:
      - target: 8080
        published: 8100
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8120
        protocol: tcp
        mode: ingress

  mano-vnfm:
    image: oviubiqube/mano-vnfm-tm22:uat2
#    environment:
#      KEYCLOAK_RESOURCE=mano-nfvo
#      KEYCLOAK_CREDENTIALS_SECRET=xxxxxxxx
    volumes:
      - "/mnt/NASVolume/mano_vnfm:/opt/etsi-mano-data"
    deploy:
      replicas: 1
      placement:	
        max_replicas_per_node: 1
        constraints:	
          - "node.labels.worker==app"
    ports:
      - target: 8080
        published: 8090
        protocol: tcp
        mode: ingress


