version: "3.8"

services:
  mano-vnfm:
    image: oviubiqube/mano-vnfm-tm22:uat4
    depends_on:
      - mano-db
    volumes:
      - "mano_vnfm:/opt/etsi-mano-data"
      
  mano-nfvo:
    image: oviubiqube/mano-nfvo-tm22:uat4
    depends_on:
      - mano-db
    volumes:
      - "mano_nfvo:/opt/etsi-mano-data"

  mano-db:
    image: openmsa/mano-db
    environment:
      POSTGRES_PASSWORD: mano
      POSTGRES_USER: mano
    volumes:
      - "mano_db:/var/lib/postgresql/data"

  mano-artemis:
    image: openmsa/artemis:2.19.0

volumes:
  mano_db:
  mano_nfvo:
  mano_vnfm:
