version: "3.8"

services:
  msa_front:
    container_name: msa_front
    image: ubiqube/msa2-front:15d25087322641746650e0bb562b6b510b40f7b4
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host
      - target: 162
        published: 162
        protocol: udp
        mode: host
   #
    # uncomment one of the 2 sections below when installing a custom certificate 
    # - Docker standard standalone installation
    #volumes:
    #    - "msa_front:/etc/nginx/ssl"
    # - Docker Swarm HA installation
    #volumes:
    #    - "/mnt/NASVolume/msa_front:/etc/nginx/ssl"
  db:
    container_name: msa_db
    image: ubiqube/msa2-db:bcff13e337fd031e81f26bab184dff9e3cb98e59
    command: postgres -c 'max_connections=800'
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "msa_db:/var/lib/postgresql/data"

  msa_api:
    container_name: msa_api
    image: ubiqube/msa2-api:436ceda580c9d2904586eac83983202b3675822e
    depends_on:
      - db
      - msa_es
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "rrd_repository:/opt/rrd"
      - "msa_dev:/opt/devops/"
      - "msa_api_logs:/opt/jboss/wildfly/standalone/log"
      - "msa_api_logs:/opt/wildfly/logs/processLog"

  msa_ui:
    container_name: msa_ui
    image: ubiqube/msa2-ui:19831ec02cdc933b497e8b5c64f76a90ca36a83d
    depends_on:
      - msa_api
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true
    - FEATURE_TOPOLOGY=true
    - FEATURE_MONITORING_PROFILES=true
    - FEATURE_SCHEDULE_WORKFLOWS=true
    - FEATURE_PROFILE_AUDIT_LOGS=true
    - FEATURE_PERMISSION_PROFILES=false

  msa_sms:
    container_name: msa_sms
    image: ubiqube/msa2-sms:7737b16a0054a40242ea60f2f17f7f098e9ffa31
    depends_on:
      - db
      - msa_es
      - msa_dev
    volumes:
      - "msa_dev:/opt/devops/"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "rrd_repository:/opt/rrd"
      - "msa_sms_logs:/opt/sms/logs"
      - "msa_svn:/opt/svnroot"
    ports:
      - "69:69"

  msa_bud:
    container_name: msa_bud
    image: ubiqube/msa2-bud:2a368ab9efa42320ce8b5060d49b954b76dd323d
    depends_on:
      - db
    volumes:
      - "msa_bud_logs:/opt/bud/logs/"

  msa_alarm:
    container_name: msa_alarm
    image: ubiqube/msa2-alarm:d760b58a932d97ca31c57ea9c32b2fb062b79e4d
    depends_on:
      - db
      - msa_es

  camunda:
    container_name: camunda
    image: camunda/camunda-bpm-platform:7.13.0

  msa_es:
    container_name: msa_es
    image: ubiqube/msa2-es:9c616a14ba0c35eb545da78bd40bf4f68d9d0d2c
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
      - bootstrap.memory_lock=true
    volumes:
      - "msa_es:/usr/share/elasticsearch/data"

  msa_cerebro:
    container_name: msa_cerebro
    image: lmenezes/cerebro:0.9.2
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"
  
  msa_kibana:
    container_name: msa_kibana
    image: ubiqube/msa2-kibana:868fb6f9e3b5ab8a5a9a346b93b8779262d9e738
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://msa_es:9200
      ELASTICSEARCH_HOSTS: http://msa_es:9200

  msa_ai_ml:
    image: ubiqube/msa2-ai-ml:b6674a077108ed42ca1fb53b9b102bf187f82a65
    ports:
      - "8000:8000"
    volumes:
      - "msa_ai_ml_db:/msa_proj/database"
    networks:
      default:
        aliases:
          - "msa-ai-ml"

  msa_dev:
    container_name: msa_dev
    build: ./lab/msa_dev
    #image: ubiqube/msa2-linuxdev:fe3982a6cb39e961b8c8dea1d6e31425a48093ed
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_dev:/opt/devops/"
      
  linux_me:
    container_name: linux_me
    # use local image for quickstart dev => for release: make sure the changes are ported to msa-docker and uncomment the line below
    #image: ubiqube/msa2-linuxme:7fc20ffaef77c39f402b6fcaa81b24540ee35850
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - DAC_READ_SEARCH
      - sys_rawio
    ports:
      - "2224:22"
    devices:                     # required for dmidecode used by polld/asset
      - "/dev/mem:/dev/mem"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me
    privileged: true

  linux_me_2:
    container_name: linux_me_2
    # use local image for quickstart dev => for release: make sure the changes are ported to msa-docker and uncomment the line below
    #image: ubiqube/msa2-linuxme:7fc20ffaef77c39f402b6fcaa81b24540ee35850
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - DAC_READ_SEARCH
      - sys_rawio
    ports:
      - "2225:22"
    devices:                     # required for dmidecode used by polld/asset
      - "/dev/mem:/dev/mem"
    networks:
      default:
        ipv4_address: 172.20.0.102
    hostname: linux_me_2
    privileged: true

volumes:
  msa_api:
  msa_db:
  msa_dev:
  msa_entities:
  msa_repository:
  msa_es:
  rrd_repository:
  msa_api_logs:
  msa_sms_logs:
  msa_bud_logs:
  msa_front:
  msa_svn:
  msa_ai_ml_db:

networks:
  default:
    name: quickstart_default
    ipam:
      config:
        - subnet: 172.20.0.0/24

