version: "3.8"

services:
  cloudclapp:
    depends_on:
      - msa-api
    image: ubiqube/cloudclapp:cf4c847245d23848cd6b10b591b42b3d214966aa
    environment:
      - UBIQUBE_CAPTCHA_SITE_KEY=6Ld2zF4dAAAAAJlqZMIHpPeb3aYhcyy1K3NWPtqi
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080"]

  ccla-scan-app:
    image: ubiqube/cloudclapp-scan:d542e628d77781003a5b1970084df4ca4239e990
    environment:
      - UBIQUBE_ZAP_TOKEN=7da091fe-63a4-48c0-9bfa-7614c49feb7c

  ccla-scan-env:
    image: owasp/zap2docker-stable
    entrypoint:
      - zap.sh
      - -daemon
      - -host
      - 0.0.0.0
      - -config
      - api.addrs.addr.name=.*
      - -config
      - api.addrs.addr.regex=true
      - -config
      - api.key=7da091fe-63a4-48c0-9bfa-7614c49feb7c

