version: "3.8"

  cloudclapp:
    depends_on:
      - msa-api
    image: openmsa/openmsa:msa2-front-2.8.0-ec00bb59447f88d2d3fef0d1a87910ffefd31f7e
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080"]
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  ccla-scan-app:
    image: ubiqube/cloudclapp-scan:d542e628d77781003a5b1970084df4ca4239e990
    environment:
      - UBIQUBE_ZAP_TOKEN=7da091fe-63a4-48c0-9bfa-7614c49feb7c
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  ccla-scan-env:
    image: owasp/zap2docker-stable
    entrypoint:
      - zap.sh
      - -daemon
      - -host
      - 0.0.0.0
      - -config
      - api.addrs.addr.name=.*
      - -config
      - api.addrs.addr.regex=true
      - -config
      - api.key=7da091fe-63a4-48c0-9bfa-7614c49feb7c
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  key-vault:
    depends_on:
      - db
    image: vault:latest
    ports:
      - "8200:8200"
    volumes:
      - ./lab/key_vault/config.hcl:/vault/config/config.hcl
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: server
