version: "3.8"

services:
  cloudclapp:
    depends_on:
      - msa-api
    image: ubiqube/cloudclapp:cf4c847245d23848cd6b10b591b42b3d214966aa
    environment:
      - UBIQUBE_CAPTCHA_SITE_KEY=6Ld2zF4dAAAAAJlqZMIHpPeb3aYhcyy1K3NWPtqi
      - UBIQUBE_LICENSE_AGREEMENT_LINK=https:\/\/cloudclapp.com\/EndUserLicenceAgreement.html
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080"]

  ccla-scan-app:
    image: ubiqube/cloudclapp-scan:d542e628d77781003a5b1970084df4ca4239e990
    environment:
      - UBIQUBE_ZAP_TOKEN=7da091fe-63a4-48c0-9bfa-7614c49feb7c

  ccla-scan-env:
    image: owasp/zap2docker-stable
    entrypoint:
      - zap.sh
      - -daemon
      - -host
      - 0.0.0.0
      - -config
      - api.addrs.addr.name=.*
      - -config
      - api.addrs.addr.regex=true
      - -config
      - api.key=7da091fe-63a4-48c0-9bfa-7614c49feb7c

  key-vault:
    depends_on:
      - db
    image: vault:latest
    ports:
      - "8200:8200"
    volumes:
      - ./lab/key_vault/config.hcl:/vault/config/config.hcl
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    command: server

  msa-sms:
    environment:
      - UBIQUBE_INSTALL_AWS_CLI=true

  msa-dev:
    command: [ "/docker-entrypoint.sh", "--cloudclapp" ]

